language: node_js
node_js:
  - '8'

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: .vuepress/dist
  on:
    branch: master
